version: '3.8'  # Use the latest compatible version

services:
  next-auth:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=mongodb://mongo:27017/project1next
      - AUTH_SECRET=FSFclrgm4a0UI527GR9Pwg
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
