import "./globals.css";

export const metadata = {
  title: "JavaProject",
  description: "Generated by create next app",
};

// Ensure variable is defined if using a custom font
// const fontVariable = "font-sans"; // Example: Replace with your actual variable

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
